from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from .embbdingService import create_and_save_index

class LLMResult(models.Model):
    """
    Stores the results generated by an LLM for a specific article and user.
    """
    utente = models.ForeignKey(User, on_delete=models.CASCADE, related_name='llm_results')
    articolo = models.ForeignKey('testo.Articolo', on_delete=models.CASCADE, related_name='llm_results')
    
    # The type of prompt/task (e.g., 'summary', 'translation', 'analysis')
    tipo_operazione = models.CharField(max_length=50)
    
    # The actual output from the LLM
    risultato = models.TextField()
    
    # Metadata for tracking performance or costs
    modello_usato = models.CharField(max_length=50, help_text="e.g., gpt-4, claude-3")
    data_creazione = models.DateTimeField(auto_now_add=True)
    tokens_usati = models.IntegerField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Risultati LLM'
        ordering = ['-data_creazione']

    def __str__(self):
        return f"{self.tipo_operazione} per {self.articolo.titolo} - {self.utente.username}"





class Document(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    faiss_index_path = models.CharField(max_length=500, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    chunks = models.JSONField(blank=True, null=True)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        index_path, chunks = create_and_save_index(self)
        self.faiss_index_path = index_path
        self.chunks = chunks
        
        # Remove force_insert if present to avoid unique constraint error on update
        kwargs.pop('force_insert', None)
        super().save(*args, **kwargs)
