# Generated by Django 5.1.4 on 2025-12-30 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testo', '0009_creazione_blacklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operazione', models.CharField(max_length=50)),
                ('risultato', models.TextField()),
                ('modello_usato', models.CharField(help_text='e.g., gpt-4, claude-3', max_length=50)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('tokens_usati', models.IntegerField(blank=True, null=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_results', to='testo.articolo')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Risultati LLM',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
