# Generated by Django 3.0.6 on 2020-05-08 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('fonte', models.CharField(max_length=50)),
                ('autore', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('testo', models.TextField()),
                ('data_caricamento', models.DateField(default=datetime.datetime.now)),
                ('frequenza_media', models.CharField(default=None, max_length=6, null=True)),
                ('quantita_termini', models.CharField(default=None, max_length=8, null=True)),
                ('complessita', models.IntegerField(default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Articolo',
            },
        ),
    ]
