# Generated by Django 3.0.6 on 2020-05-07 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='data_caricamento',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='articolo',
            name='frequenza_media',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='articolo',
            name='quantita_termini',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
