# Generated by Django 3.0.6 on 2020-05-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testo', '0002_auto_20200507_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='complessita',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
