# Generated by Django 3.0.6 on 2020-05-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testo', '0003_articolo_complessita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parola', models.CharField(max_length=30)),
                ('occorrenze', models.IntegerField(default=None, null=True)),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testo.Articolo')),
            ],
        ),
    ]
