# Generated by Django 3.0.6 on 2020-05-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testo', '0004_Aggiunta_tabella_termini'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=30, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.AlterModelOptions(
            name='articolo',
            options={'verbose_name_plural': 'Articolo'},
        ),
    ]
