# Generated by Django 3.0.6 on 2020-05-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testo', '0005_creazione_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testo.Utente'),
        ),
    ]
