# Generated by Django 3.0.6 on 2020-05-10 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testo', '0006_creazione_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
