# Generated by Django 3.0.6 on 2020-05-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testo', '0007_AssegnataUserFKaArticolo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utente',
        ),
    ]
