# Generated by Django 5.1.4 on 2026-02-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testo', '0009_creazione_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='ai_rating',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='articolo',
            name='clarity_score',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='articolo',
            name='final_score',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='articolo',
            name='lexical_diversity',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='articolo',
            name='readability_score',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='articolo',
            name='spelling_score',
            field=models.FloatField(default=None, null=True),
        ),
    ]
